// Code generated by protoc-gen-go. DO NOT EDIT.
// source: referenceproto.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReferenceProto struct {
	Orig                 string   `protobuf:"bytes,1,opt,name=orig,proto3" json:"orig,omitempty"`
	Destination          string   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferenceProto) Reset()         { *m = ReferenceProto{} }
func (m *ReferenceProto) String() string { return proto.CompactTextString(m) }
func (*ReferenceProto) ProtoMessage()    {}
func (*ReferenceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ef9a11f4cb6a1ed, []int{0}
}

func (m *ReferenceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceProto.Unmarshal(m, b)
}
func (m *ReferenceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceProto.Marshal(b, m, deterministic)
}
func (m *ReferenceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceProto.Merge(m, src)
}
func (m *ReferenceProto) XXX_Size() int {
	return xxx_messageInfo_ReferenceProto.Size(m)
}
func (m *ReferenceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceProto proto.InternalMessageInfo

func (m *ReferenceProto) GetOrig() string {
	if m != nil {
		return m.Orig
	}
	return ""
}

func (m *ReferenceProto) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*ReferenceProto)(nil), "main.ReferenceProto")
}

func init() { proto.RegisterFile("referenceproto.proto", fileDescriptor_1ef9a11f4cb6a1ed) }

var fileDescriptor_1ef9a11f4cb6a1ed = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x4d, 0x4b,
	0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0x2c, 0xb9,
	0x89, 0x99, 0x79, 0x4a, 0x6e, 0x5c, 0x7c, 0x41, 0x30, 0xd9, 0x00, 0xb0, 0xb8, 0x10, 0x17, 0x4b,
	0x7e, 0x51, 0x66, 0xba, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0xa4, 0xc0, 0xc5,
	0x9d, 0x92, 0x5a, 0x5c, 0x92, 0x99, 0x97, 0x58, 0x92, 0x99, 0x9f, 0x27, 0xc1, 0x04, 0x96, 0x42,
	0x16, 0x4a, 0x62, 0x03, 0x1b, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xef, 0x3f, 0x5e, 0xbc,
	0x6c, 0x00, 0x00, 0x00,
}
